### ISSUE TITLE
Something seems to corrupt _self

### ISSUE THREAD

**Issue by bushidocodes** [bushidocodes/chord-grpc#37]
_self is set to null or some other value, which causes an error to throw, when the id property is attempted to be accessed below

```js
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 128)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 130)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 132)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 134)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 136)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 138)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 140)
find_successor's call to find_predecessor failed with  TypeError: Cannot read property 'id' of undefined
    at find_predecessor (/home/sean/projects/chord-grpc/node.js:315:63)
    at async find_successor (/home/sean/projects/chord-grpc/node.js:176:17)
    at async fix_fingers (/home/sean/projects/chord-grpc/node.js:1211:19)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
fix_fingers call to find_successor failed with  TypeError: Cannot read property 'id' of undefined
    at fix_fingers (/home/sean/projects/chord-grpc/node.js:1212:21)
    at async Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1364:5)
(node:7348) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at stabilize (/home/sean/projects/chord-grpc/node.js:1058:60)
    at Timeout._onTimeout (/home/sean/projects/chord-grpc/node.js:1361:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by bushidocodes** [comment]
Resolved by #77
