### ISSUE TITLE
Crawler logic to clean up view of overlay network errors

### ISSUE THREAD

**Issue by bushidocodes** [bushidocodes/chord-grpc#41]
}
Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/home/sean/projects/chord-grpc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses'
}
Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/home/sean/projects/chord-grpc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses'
}
Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/home/sean/projects/chord-grpc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/sean/projects/chord-grpc/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses'
}

**Comment by roxie-23** [comment]
how to solve this bug?
