### ISSUE TITLE
updateSuccessorTable errors out

### ISSUE THREAD

**Issue by bushidocodes** [bushidocodes/chord-grpc#94]
I'm seeing this error a bunch:
```
node_secondary_11 | stabilize: updateSuccessorTable failed with  TypeError: Cannot read property 'id' of undefined
node_secondary_11 |     at UserService.<anonymous> (/home/node/app/ChordNode.ts:921:36)
node_secondary_11 |     at step (/home/node/app/ChordNode.ts:33:23)
node_secondary_11 |     at Object.next (/home/node/app/ChordNode.ts:14:53)
node_secondary_11 |     at fulfilled (/home/node/app/ChordNode.ts:5:58)
node_secondary_11 | stabilize: updateSuccessorTable failed with  TypeError: Cannot read property 'id' of undefined
node_secondary_11 |     at UserService.<anonymous> (/home/node/app/ChordNode.ts:921:36)
node_secondary_11 |     at step (/home/node/app/ChordNode.ts:33:23)
node_secondary_11 |     at Object.next (/home/node/app/ChordNode.ts:14:53)
node_secondary_11 |     at fulfilled (/home/node/app/ChordNode.ts:5:58)
node_secondary_11 | stabilize: updateSuccessorTable failed with  TypeError: Cannot read property 'id' of undefined
node_secondary_11 |     at UserService.<anonymous> (/home/node/app/ChordNode.ts:921:36)
node_secondary_11 |     at step (/home/node/app/ChordNode.ts:33:23)
node_secondary_11 |     at Object.next (/home/node/app/ChordNode.ts:14:53)
node_secondary_11 |     at fulfilled (/home/node/app/ChordNode.ts:5:58)
```

It looks like `this.successorTable[i].id` is undefined below:
```js
          !isInModuloRange(
            successorSuccessor.id,
            this.id,
            true,
            this.successorTable[i].id,
            true
          )
```

**Comment by bushidocodes** [comment]
Fixed by 8e7904c ("chore: assorted cleanup", 2019-12-29).

This was a race condition, not a missing null check. `stabilize()` is scheduled via `setInterval(stabilize, 1000)` but is `async` with multiple `await`s, so at the time this was filed a new stabilize fired every second while the previous one was still suspended. Two `updateSuccessorTable` runs could interleave: one would `shift()`/`pop()` the `successorTable` while the other sat suspended at `await this.getSuccessor(this.successorTable[i])` in the bulk-up loop, so on resume `this.successorTable[i]` was `undefined` and `this.successorTable[i].id` threw.

8e7904c added the `stabilizeIsLocked` gate, which serializes `stabilize()`. Since `updateSuccessorTable()` is only ever called from inside `stabilize()` (single call site) and the only array-shrinking mutations (shift/pop) live inside `updateSuccessorTable` itself, no concurrent run can mutate the table during the `await`, and the TypeError can no longer occur. Closing as fixed.
